version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run: bundle check || bundle install
      - run:
          command: bundle exec rspec spec
          when: always
      - store_test_results:
          path: test/reports
